### ISSUE TITLE
User test cases file

### ISSUE THREAD

**Issue by Hana-ElGabry** [Hana-ElGabry/CareerPilot#21]
### here the user test cases for the program shall be uploaded

**Comment by mariambasem** [comment]
[testcase3.docx](https://github.com/user-attachments/files/18218750/testcase3.docx)

**Comment by Hana-ElGabry** [comment]
try to push your files here @zeinaaahmedd

**Comment by mariambasem** [comment]
[testcase4.docx](https://github.com/user-attachments/files/18220198/testcase4.docx) #22
